[workspace]
members = ["kernel", "xtask"]

[workspace.dependencies]
anyhow = "1.0"
bootloader = "0.11"
bootloader_api = "0.11"
clap = { version = "4.5", features = ["derive"] }
num-traits = { version = "0.2", default-features = false }
